apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.roleType }}Binding
metadata:
  name: incluster-kubectl-apply-job-binding
  {{- if eq .Values.roleType "Role" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.roleType }}
  name: {{ .Values.roleName }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: incluster-kubectl-apply-job-sa
